# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-23 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_blog_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='unique_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
